### ISSUE TITLE
How can we show calling screen  and user accept & decline video call (Like video chat)

### ISSUE THREAD

**Issue by jigarfumakiya** [AgoraIO-Community/Agora-Flutter-Quickstart#15] opened 2019-05-01 04:50 UTC
How a user can show calling screen so the user can accept and decline Video call.

anyone know how this can be done

thanks

**Comment by pavankumarkatakam** [comment] 2019-05-05 09:48
Hi @jigarfumakiya , did you find any information on that, im looking for the same.

**Comment by PRWrl** [comment] 2019-05-05 11:50
Calling screen can be shown using [CallKit(iOS)](https://developer.apple.com/documentation/callkit) and [ConnectionService(Android)](https://developer.android.com/reference/android/telecom/ConnectionService), but there are no available flutter package in pub I think.

**Comment by pavankumarkatakam** [comment] 2019-05-06 04:47
Hi @PRWrl, I have seen this native android project is this what you are talking about.

https://github.com/AgoraIO/Advanced-Video/tree/master/Calling-Interface/Agora-RTC-With-ConnectionService-Android

**Comment by PRWrl** [comment] 2019-05-06 04:55
Yes, and there is also demo for native iOS: https://github.com/AgoraIO/Advanced-Video/tree/master/Calling-Interface/Agora-RTC-With-CallKit

**Comment by jigarfumakiya** [comment] 2019-05-06 05:10
Hey @PRWrl  that is native android& ios projects, I think we need in a flutter.

**Comment by plutoless** [comment] 2019-05-12 14:27
@jigarfumakiya as @PRWrl mentioned above you will need a flutter package to show calling screen, which is currently not included in our SDK

**Comment by jigarfumakiya** [comment] 2019-05-14 12:51
yeah, I understand.

Thanks for letting me know

**Comment by pavankumarkatakam** [comment] 2019-05-30 05:30
@PRWrl , Actually i need to open app it self to show accept or reject screen in receiver side, but the connection service or native project is not doing that.

**Comment by PRWrl** [comment] 2019-05-30 11:02
In that case, you will need [GCM/FCM](https://firebase.google.com/docs/cloud-messaging/) for Android, and [VoIP Push Notification](https://developer.apple.com/documentation/pushkit) for iOS.

**Comment by jigarfumakiya** [comment] 2019-05-30 11:07
> In that case, you will need [GCM/FCM](https://firebase.google.com/docs/cloud-messaging/) for Android, and [VoIP Push Notification](https://developer.apple.com/documentation/pushkit) for iOS.

Yes you Right
But in that case, we need to write Both native codes and handle native code so that more changes to fail.
now we don't have anything so we can do Using  GCM/FCM

**Comment by jigarfumakiya** [comment] 2019-05-30 11:09
@PRWrl  so there are any changes that you guys are working on that kind of feature and Push.

**Comment by PRWrl** [comment] 2019-05-30 11:10
There're some plugins like [firebase_messaging](https://pub.dev/packages/firebase_messaging), you can have a try.

**Comment by jigarfumakiya** [comment] 2019-05-30 11:15
> There're some plugins like [firebase_messaging](https://pub.dev/packages/firebase_messaging), you can have a try.

I know that. @PRWrl 
And  thanks for your contribution & your All help

**Comment by pavankumarkatakam** [comment] 2019-05-30 12:28
Im already working messaging angle also and almost achieved but is there anything that we can do with some agora network. (I dont know SIP, signaling etc but just asking)

**Comment by pavankumarkatakam** [comment] 2019-05-30 12:30
@PRWrl , Do you think whatsapp also opening the acceptance screen with push notification?

**Comment by jigarfumakiya** [comment] 2019-05-30 12:51
> @PRWrl , Do you think whatsapp also opening the acceptance screen with push notification?

I don't think so whatsapp show you screen not push notification

**Comment by pavankumarkatakam** [comment] 2019-05-30 13:01
Yeah i know that, But how whatsapp itself opening the screen (Acceptance screen) . My though was they are sending the FCM data message (not notification message) and starting the voip activity. (I have seen thier ADB logs they named thier activity as voip activity)

**Comment by jigarfumakiya** [comment] 2019-07-11 12:52
yes I have done with FCM and Android and also IOS and that working good

**Comment by pavankumarkatakam** [comment] 2019-07-12 04:05
How did you do that @jigarfumakiya , please provide some samples or anything.

**Comment by jigarfumakiya** [comment] 2019-07-12 11:41
@pavankumarkatakam I did it using FCM in Android and also in IOS.

Solution is 
I sent a notification to Device-to- Device using cloud notification. and I also sent data with notification and then onResume()&OnMessage() method I open a new page called acceptance screen but that show when a user clicks on the notification. (that working if the app is in the background).
if the app is in foreground then automaticity  open acceptance screen
I know  I haven't achieved completely What's app functionality. but that working good.


let me know what you think...

**Comment by pavankumarkatakam** [comment] 2019-07-12 11:45
So far i too did what you said, but im looking for what exactly whatsapp is doing.

**Comment by jigarfumakiya** [comment] 2019-07-12 12:45
yes, sure I also looking for that if you find it let me know @pavankumarkatakam

**Comment by jigarfumakiya** [comment] 2019-07-26 05:36
hey, @pavankumarkatakam I think you can achieve whats'app call functionality in Android using service and In ios, I don't know yet.

**Comment by kamrancr7** [comment] 2019-08-16 18:19
Any update on that issue??

**Comment by JonathanJude** [comment] 2020-01-08 21:07
@jigarfumakiya  i want to achieve same with FCM too.. mind sharing code samples on how you did that?

**Comment by LichKing-2234** [comment] 2020-04-22 04:17
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Closed by LichKing-2234** 2020-04-22 04:17 UTC

**Comment by sagar440** [comment] 2020-07-15 05:59
Hi @jigarfumakiya , @pavankumarkatakam , i am also looking for the same that whatsapp doing and i'm using 
[.](https://pub.dev/packages/agora_rtc_engine) package with flutter. have you found any proper solution. for any suggestion or help highly appreciate in advance.

**Comment by zeeshan1010** [comment] 2020-08-07 07:12
@LichKing-2234 @jigarfumakiya any update on this guys? for acceptance screen like whatsapp?

**Comment by LichKing-2234** [comment] 2020-08-07 07:47
@zeeshan1010 as above, you can use FCM to send a notification?

**Comment by zeeshan1010** [comment] 2020-08-07 07:59
@LichKing-2234 with FCM user have to click on notification for openning acceptance screen.Is there any otherway to show direct acceptance screen when user get call when app is in backgound,killed or mobile is in lock mode like whatsapp,fb and other social media apps?

**Comment by LichKing-2234** [comment] 2020-08-07 08:10
@zeeshan1010 
Calling screen can be shown using [CallKit(iOS)](https://developer.apple.com/documentation/callkit) and [ConnectionService(Android)](https://developer.android.com/reference/android/telecom/ConnectionService).

**Comment by zeeshan1010** [comment] 2020-08-07 08:23
@LichKing-2234 yes i checked with this in many comments but any real time implementation(demo project) availbale with agora_rtc_engine)? which we can checkout?

**Comment by zeeshan1010** [comment] 2020-08-07 08:24
@LichKing-2234 yes i checked this in many comments but any real time implementation(demo project) availbale with agora_rtc_engine)? which we can checkout?

**Comment by jigarfumakiya** [comment] 2020-08-10 07:15
@zeeshan1010 you can achieve this in Android using service make service and run in the background and wait for your event call.

**Comment by tushardubey121** [comment] 2020-09-03 10:56
Hey, @**jigarfumakiya** please reopen this. there is no update on that. I am also using firebase to chive that functionality.

**Comment by uwbobanminic** [comment] 2020-10-06 13:43
Any updates on this?

Some demo project or proper solution?

We are creating platform with audio/video calls and I need to receive calls when app is in background. I managed it when the app is in foreground trough sockets, and then redirecting user to browser instance of the app, but when app is in background, i didn't find solution yet, because even with FCM, sometimes there is a lot of delay until it arrives to device.

**Comment by prozaklob** [comment] 2020-10-07 03:13
> Any updates on this?
> 
> Some demo project or proper solution?
> 
> We are creating platform with audio/video calls and I need to receive calls when app is in background. I managed it when the app is in foreground trough sockets, and then redirecting user to browser instance of the app, but when app is in background, i didn't find solution yet, because even with FCM, sometimes there is a lot of delay until it arrives to device.


Could you share an example of how you implemented a call through FCM?

**Comment by mayankmikin** [comment] 2020-12-20 11:47
I am looking for an example of whats app call through FCM , where a user can accept and decline it . on accepting it will open the app and then through background handler navigate to the proper page ?

**Comment by kimoduor** [comment] 2020-12-20 11:50
You can make it ring while in the background. When the user clicks fcm
notification, it opens the app on the desired page. Thats how i forced to
do mine

**Comment by EgHubs** [comment] 2021-01-17 19:19
> You can make it ring while in the background. When the user clicks fcm notification, it opens the app on the desired page. Thats how i forced to do mine

and how do I make it ring?

**Comment by kimoduor** [comment] 2021-02-13 18:05
I coded in flutter and tested in Android
So I use firebase_messaging(https://pub.dev/packages/firebase_messaging) that you have to specify channel_id in the manifest.
From the server, the message comes with a ringtone string.
You have to put the rington file in android\app\src\main\res\raw in my case, mine is call.mp3
Here is my php curl in the server
 $key = "THIS_isTHE_FIREBASE_KEY";
        $data = '{"notification": { "title": "Requesting...","body":" A New Request. Tap Here to Open...",  "sound": "call","image":"' . $image . '","icon":"logo","color":"#FF0000" },"time_to_live": 60, "data" :' . 'message' . ',"priority":"high", "to" :"' . $fcm_token . '"}';
        $ch = curl_init("https://fcm.googleapis.com/fcm/send");
        $header = array('Content-Type: application/json', 'Authorization: key=' . $key);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        $out = curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_exec($ch);
        curl_close($ch);

**Comment by Faiizii** [comment] 2021-05-17 06:11
I am facing the same problem but nothing found for exact solution. But I have an android ringing notification using [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) like 
````
FlutterLocalNotificationsPlugin().show(
      0,
      'Title here',
      'Body here',
      NotificationDetails(
          android: AndroidNotificationDetails(
              'call_handler_132',
              'incoming call',
              'Notification channel for incoming call handling',
              priority: Priority.high,
              importance: Importance.max,
              fullScreenIntent: true,
              timeoutAfter: 10000,
              sound: RawResourceAndroidNotificationSound('path to sound file'),
              playSound: true,
              additionalFlags: Int32List.fromList(
                  <int>[4]) //help to continue ringing of notification
              ),
          iOS: IOSNotificationDetails(
              //sound: "assets/notification_ring.mp3"
              )));
````

What I want to achieve? 
I want to open my custom designed acceptance screen on receiving notification. The problem is that there is no context inside the notification handler of [firebase_messaging](https://pub.dev/packages/firebase_messaging) due to which I am unable to open custom designed widget. I asked it on both repo issues messaging and flutter and no one is willing to accept the advancement sadly. 
Is there any suggestion about this topic ?

**Comment by sicklestudios** [comment] 2023-02-11 20:30
Any updates on the issue? I guess the issue is still not solved.

**Comment by viveklc** [comment] 2024-04-09 18:30
It seems it is not solved yet.

Masters who have achieved this ringing feature can share their code so others can have some help.

**Comment by adnan-haider007** [comment] 2024-06-04 00:38
there is another question which is if user want to reject the call then how it will happens?
