### ISSUE TITLE
Problem on video Flutter-Ios #3

### ISSUE THREAD

**Issue by laxmanatwebifi** [AgoraIO-Community/Agora-Flutter-Quickstart#30] opened 2019-09-13 09:48 UTC
In iOS, the screen is blank. 
I entered the same channel from android, there, I can see the video being rendered from the iOS  as well. In IOS too, the sound is coming. Only the issue is video is not being rendered in ios. I already read the closed issue on the same problem. There he has permission issues. I already give the permission and still the screen is blank.

**Comment by plutoless** [comment] 2019-09-13 11:41
please provide flutter doctor and screenshot of your black screen

**Comment by laxmanatwebifi** [comment] 2019-09-13 12:36
![ios_not_rendering_video](https://user-images.githubusercontent.com/24522486/64862815-2a311480-d653-11e9-8873-fa3a74d49c58.png)

**Comment by plutoless** [comment] 2019-09-13 12:38
have you changed anything with our quickstart demo? it does not look quite the same. will you have issue if you run our quickstart directly?

**Comment by laxmanatwebifi** [comment] 2019-09-13 12:42
no not in the logic, I just changed the appbar. When I run without editing any of the code, it still has the same problem in iOS. In android, screen from ios is rendering properly.

![hello123](https://user-images.githubusercontent.com/24522486/64863215-0b7f4d80-d654-11e9-85d6-add8321b8f3a.jpg)

**Comment by laxmanatwebifi** [comment] 2019-09-16 06:41
Hi, 
I again just launch your code directly without touching any code. In i0S, it has problem rendering the video. Is this the permission issues? I have given following permissions as well.
Privacy - Microphone Usage Description
Privacy - Camera Usage Description

**Comment by Matrixbirds** [comment] 2019-09-17 07:54
I cannot reproduce it with flutter **version v1.7.8+hotfix.4**, please pates your `flutter doctor` result here.

**Comment by laxmanatwebifi** [comment] 2019-09-17 11:37
@Matrixbirds 
flutter doctor result:[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030, locale en-NP)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.38.1)
[!] Connected device
    ! No devices available

I have tested this code in 1.7.8+hotfix.4. At that time also, I was experiencing the same issue.
Agora_rtc_engine version used is 1.0.0 [ But previously when I used 0.9.8 a month ago, the same issue I faced.

**Comment by wuichen** [comment] 2019-09-24 17:43
having same problem on the latest flutter as well

**Comment by Matrixbirds** [comment] 2019-09-25 05:42
@wuichen  Can u provide more flutter doctor and other details here?

**Comment by laxmanatwebifi** [comment] 2019-09-25 06:50
@Matrixbirds 
I have flutter doctor report sent above. What could be the problem?

**Comment by Matrixbirds** [comment] 2019-10-14 03:16
@laxmanatwebifi  It works fine in my side.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

• No issues found!

Can u please try to build the quickstart with flutter v1.9.1+hotfix.2 again ? We just update to the 1.0.1 and using the AgoraWidgetRender for render video.

**Comment by husmen73** [comment] 2019-10-19 20:14
I have same problem on ios. Android devices working as normal. I'm getting camera video streaming from ios on android device but can not see anyone video on ios device.

`[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Developer/Android Studio.app/Contents/MacOS/studio/Contents
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (4 available)
`

**Comment by Matrixbirds** [comment] 2019-10-31 17:29
Can u pls provide your log here both ipad & ios device.

**Comment by duongtruong12** [comment] 2019-11-29 11:48
> Can u pls provide your log here both ipad & ios device.

i had faced the same issue did this issue solved?

**Comment by a2hs** [comment] 2020-03-10 03:50
Maybe you need to add the following two lines to Info.plist under the ios/Runner.
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Comment by LichKing-2234** [comment] 2020-04-22 04:18
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Closed by LichKing-2234** 2020-04-22 04:18 UTC
