### ISSUE TITLE
enableLocalVideo and muteLocalVideoStream Not working

### ISSUE THREAD

**Issue by sajanyamaha** [AgoraIO-Community/Agora-Flutter-Quickstart#223] opened 2021-04-15 08:40 UTC
Ultimate aim is to Mute/Unmute Video .

Trying on version ,
  **agora_rtc_engine: ^3.3.3
  permission_handler: ^5.1.0+2**

On trying to mute local video , the video never stops ,
enableLocalVideo - There is a small glitch and video continue recording
muteLocalVideoStream - No effect 

```
_muteCamera() async {
    //await widget._engine?.muteLocalVideoStream(true);
    await widget._engine?.enableLocalVideo(false);
    setState(() {
      isCameraMute = true;
    });
  }

  _unMuteCamera() async {
    await widget._engine?.enableLocalVideo(true);
    //await widget._engine?.muteLocalVideoStream(false);
    setState(() {
      isCameraMute = false;
    });
  }
```
Logs at that instantce ,
_E/agora_vrp(14043): replaced by swap before render. gap=45 ms. all replaced by swap=1, stream=203280232
E/BufferQueueProducer(14043): [ImageReader-640x480f23m2-14043-11] cancelBuffer: BufferQueue has been abandoned
E/libc    (14043): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14043): Access denied finding property "persist.vendor.camera.privapp.list"
E/libc    (14043): Access denied finding property "vendor.camera.aux.packagelist"
E/agora_vrp(14043): replaced by swap before render. gap=108 ms. all replaced by swap=2, stream=203280232
E/libc    (14043): Access denied finding property "net.dns1"
E/libc    (14043): Access denied finding property "net.dns2"
E/libc    (14043): Access denied finding property "net.dns3"
E/libc    (14043): Access denied finding property "net.dns4"
I/agora_vrp(14043): stuck_watch: fps=11, id=0
I/agora_vrp(14043): stuck_watch: total=22, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=13%, 60~80=77%, 80~110=4%, 110~150=0%, 150~200=0%, 200+=4%, id=0
I/agora_vrp(14043): stuck_watch: 100+ms=617, id=0
I/agora_vrp(14043): stuck_watch: interval_distribution=467354517508, sd:11508, id:0, avg draw cost:1
I/agora_vrp(14043): Frames rendered=22. Render Fps=11, Total rendered=740, stream=0, draw cost=22, 0, 0, 0, 0, 0, render inter=0, 0, 0, 3, 17, 1, 0, 0, 1
I/GDPAndroid(14043): getCpuTemperature valid path:/sys/class/thermal/thermal_zone0/temp
I/agora_vrp(14043): stuck_watch: 100+ms=615, id=0
I/agora_vrp(14043): stuck_watch: sd:11436, id:0_

**Comment by plutoless** [comment] 2021-04-18 04:49
duplicate of https://github.com/AgoraIO/Agora-Flutter-SDK/issues/301
please follow that issue instead. i will close this one here.

**Closed by plutoless** 2021-04-18 04:49 UTC
